[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Yokai Batch"
authors = [{name = "Yann Eugoné", email = "eugone.yann@gmail.com"}]
dynamic = ["version", "description"]
